name: Build de4dot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - run: nuget restore de4dot.netframework.sln
      - run: msbuild de4dot.netframework.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /m
      - uses: actions/upload-artifact@v4
        with:
          name: de4dot-netfx
          path: |
            **/Release/*.exe
            **/Release/*.dll
            !**/*.pdb
